CREATE ROLE app_user WITH LOGIN ENCRYPTED PASSWORD 'changeme123';
ALTER ROLE app_user WITH NOLOGIN;
CREATE SCHEMA IF NOT EXISTS app;
GRANT USAGE ON SCHEMA app TO app_user;
GRANT CREATE ON SCHEMA app TO app_user;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO app_user;
ALTER USER app_user SET search_path = app, public;
